// <auto-generated />
namespace ConcordyaPayee.Web.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changeUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201412231544369_changeUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
